### ISSUE TITLE
Analyze and update requirements

### ISSUE THREAD

**Issue by elif-caliskan** [bounswe/bounswe2019group4#119]
**Deadline: 30.09.19 Monday @23.59** 
You should inform the customer if you want to add or remove any requirement.

**Comment by leventbass** [comment]
@cemalaytekin, @gurkandemir and I will be discussing about possible necessary revisions in our Slack channel. We will be in contact with the customer throughout the review process and act **according to the customer's feedback.**

**Comment by gurkandemir** [comment]
For that reason, we have created a new channel named _*revise_requirements*_ in our group’s workspace.

**Comment by gurkandemir** [comment]
I have analyzed _**functional requirments.**_ We will update requirements, listed below.

- __1.1.2.2 Login:__ We need to add, _Users shall login via Google account._
- __1.1.2.2 Login:__ We need to add, _Users shall be able to reset their passwords if they forget their passwords by clicking **"Forget password?"** button._
- __1.1.3.3:__ We need to update it: _Users shall be able to accept or reject following requests._
- __1.1.5 Profile:__ We need to add: _Users shall be able to reach their own followers and followings list in their profile page._
- __1.1.7 Portfolio:__ We need to add: _Users shall be able to create/delete their portfolios._
- __1.1.7.4:__ We need to update it: _Users shall be able to add or remove trading equipments from/to portfolio._

***

Beside of those, we will insert new section **1.1.10 Events**
- __1.1.10.1:__ _Users shall be able to see events fetched from third parties._
- __1.1.10.2:__ _Users shall be able to comment on events._
- __1.1.10.3:__ _Users shall be able to filter events by its currency, significance level, location etc._

**Comment by leventbass** [comment]
Proposed additonal requirements and revisions are as follows:

- We should add _**1.1.2. Registered Users**_ requirement and add all of the subsequent requirements under _**1.1.2**_ as sub-requirements, since **_1.1.3._**, **_1.1.4._**, **_1.1.5._**, **_1.1.6._**, **_1.1.7._**, **_1.1.8._** and **_1.1.9._** cannot be at same level hiearchically as **_1.1.1._** considering that they cannot be linked semantically to guest users' requirements in **_1.1.1._**
- We should move the registration requirement **_1.1.2.1._** with all of its sub-requirements under the **_1.1.1. Guests_**,  since only guest users can register and registered users cannot register more than once.
- Under System Requirements a new requirement should be added to elaborate on account validation such as:
    *  **1.2.1. User Authentication**
    *  **1.2.1.1.** _A confirmation link shall be sent to the users' email address for authentication._
    *  **1.2.1.2.** _After clicking the confirmation link, users shall be registered to their account and logged in automatically._
- After the addition of **_1.1.10. Events_** as proposed by @gurkandemir, the following sub-requirement should be added as well:
    *  **1.1.10.4.** _Users shall be able to set an alarm to a specific event._
- After adding the requirement _"Users shall be login via Google account"_ as proposed by @gurkandemir, we should also add the following requirements to the registration requirements part:
    * _Users shall be able to register via their Google accounts._
    * _Trading users shall be able to register via their Google accounts, given that they provide IBAN and T.C. identification number additionally._
- In the light of all new additions and modifications, requirements should be renumbered properly.

**Comment by gurkandemir** [comment]
Totally agree with @leventbaas , additionally we have to review system and nonfunctional requirements in detail.

@cemalaytekin !

**Comment by leventbass** [comment]
If it's ok with @mericturan I will start making necessary changes to the requirements as we have discussed here.

**Comment by cemalaytekin** [comment]
I have analyzed system requirments. As I am a new member of this project, I want to make the following requirements more clear:

* 1.2.2.2 System shall send notification to users according to their alerts.
    * What do we mean by "alerts" ? We can update this requirement as:

      1.2.2.2 The system shall provide a notification mechanism which lets traders to get notified (or alerted) about certain levels of trading equipment.

* 1.2.4.2 Events shall be able to have different significance levels
* 1.2.4.3 Events shall have numerical results.
   * I think, the system requirements must start with "the system shall...". These two requirement can be updated as:
      1.2.4.2 The system shall be able to provide different significance levels for events.
      1.2.4.3 The system shall provide numerical results for events.

@gurkandemir @leventbass What do you think about these requirements?

**Comment by gurkandemir** [comment]
Updated [requirements analysis.](https://github.com/bounswe/bounswe2019group4/wiki/Requirements-Analysis)
