### ISSUE TITLE
Backend User Profile Page Extras

### ISSUE THREAD

**Issue by bahadirh** [bounswe/bounswe2019group4#251]
Our API returns status code 400 when another user that's not following that user requested to view his profile. It would be more appropriate to return at least the user's basic info, like his name and surname and whether his profile is public or not.

**Comment by gurkandemir** [comment]
- [ ] If user is not following visiting profile which is private, at least I should see name, surname, number of followers and followings,
- [ ] If user is following visiting profile, I should see name, surname, isPublic, isTrader, followings, followers with their lengths, email, location, following trading equipments
- [ ] If I am visiting my page, I should see additionally iban, tckn etc in order to modify
