### ISSUE TITLE
Review Use Case Diagram After Feedback

### ISSUE THREAD

**Issue by oztasozgurcan** [bounswe/bounswe2019group4#48]

**Comment by uskudarli** [comment]
It would be useful to provide the feedback or a reference to it. 

And to make specific assignments to each team member.

In general, you should expect to have description in tasks.

I suppose once they are done you want someone else to review them.

**Comment by gurkandemir** [comment]
Related feedbacks about use-case diagram:

- "According to your use case diagram, Guest Users can comment on trading equipment, add trading equipment to their protfolios, and set alarms for trading equipment, which is incorrect."
- "In use case diagram, the direction for extended lines are incorrect. They should be reversed."
- "In use case diagram, Enter Credentials should include Check Credentials, rather than Login."
- "In use case diagram, Enter Location->Select Location"
- "In use case diagram, what you refer as manual investing is manual entry for profil/loss calculation"
- "What is the relation between Profile and Edit Profile (i.e., include or extend)? Specify it. Also, apply the same methodology for the rest of use case diagram"
- "For use case diagrams, check "use case generalization" and apply this method to your use case diagram."
- "In use case diagram, do you have search portfolio functionality by providing trading equipment?"
- "I cannot see profil/loss amount for investments in use case diagrams."

**Comment by oztasozgurcan** [comment]
I've made changes into diagram. Search, comment and set alarms were separated, now they are generalized, further selections given as options which are "extend" operations. Can you review, @gurkandemir ?

**Comment by gurkandemir** [comment]
In my opinion, it would be better if we put all same kind of things together. For example, we can categorize search user profile, search trading equipments etc under the title named **Search**. Same applies for **comments and alarms**.

**Comment by gurkandemir** [comment]
Other than this, this version -after feedback- looks better and simpler than previous one.

**Comment by oztasozgurcan** [comment]
> In my opinion, it would be better if we put all same kind of things together. For example, we can categorize search user profile, search trading equipments etc under the title named **Search**. Same applies for **comments and alarms**.

**Done.**
