### ISSUE TITLE
Prepare the second draft of the project plan

### ISSUE THREAD

**Issue by leventbass** [bounswe/bounswe2019group4#64]
I will be creating a new version of the project plan according to the feedback given by our team members.

**Comment by elif-caliskan** [comment]
I want to add three new tasks and change some dates of the existing tasks based on [Meeting Notes 2](https://github.com/bounswe/bounswe2019group4/wiki/Meeting-Notes-%232):
1. Preparing the draft of questions 2 days: 18.02.19 13.00 - 20.02.19 13.00
2. Preparing a clear list of questions 1 day: 20.02.19 13.00 - 21.02.19 13.00
3. Meeting with customer : 20.02.19 13.00 - 22.02.19 13.00
4. Documenting the questions and answers 3 days: 21.02.19 17.00 - 24.02.19 17.00
5. Creating the first draft of requirements 3 days: 19.02.19 17.00 - 22.02.19 17.00
6. Discussing the first draft of the requirements with customer 1 day: 22.02.19 17.00- 23.02.19 17.00
7. Revising and finalizing the requirements and glossary 1 day: 23.02.19 17.00- 24.02.19 17.00
Since we met with the customer twice, I added customer meetings before and after the finalization of draft. 
1 -> 2, 1->3, 2->4, 5->6, 6->7
Open for any feedbacks @baturalp-yoruk

**Comment by baturalp-yoruk** [comment]
I think, it is completely OK, after adding the assignees. Thank you @elif-caliskan

**Comment by baturalp-yoruk** [comment]
So you can add this part to the Project Plan @leventbass , thank you in advance.

**Comment by leventbass** [comment]
Thanks @elif-caliskan and @baturalp-yoruk, I will revise the project plan upon your feedback. Any other feedback is also welcome.

**Comment by gurkandemir** [comment]
Is there any update with this issue? If so, could you share current status with us in order to review?

**Comment by leventbass** [comment]
Could you give your feedback regarding the first draft of the project plan? I will finish revising the plan once I collect enough feedback. 

> Is there any update with this issue? If so, could you share current status with us in order to review?

Could you give your feedback regarding the first draft of the project plan? I will finish revising the plan once I collect enough feedback. @gurkandemir

**Comment by leventbass** [comment]
I have created the new version of our project plan. Hence, I'm closing this issue now.
